#Environment dev
version: '3'
services:
  prod:
    build: 
      context: .
    image: "mint-project/ui"
    volumes:
      - ./config-dev.js:/usr/share/nginx/html/config.js
    ports:
      - 8000:80        
