#Environment dev
version: '3'
services:
  prod:
    build: 
      context: .
    image: "mint-project/ui"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 12122:80        
