#import "../fragments/thread-info.graphql"
#import "../fragments/execution-summary-info.graphql"

subscription sub_thread($id: String!) {
  thread_by_pk(id: $id) {
    ...thread_info
    thread_data {
      dataslice {
        id
        dataset {
          id
          name
        }
        resources {
          selected
          resource {
            id
            name
            dcid
          }
        }
        start_date
        end_date
        selected_resources: resources_aggregate(
          where: { selected: { _eq: true } }
        ) {
          aggregate {
            count
          }
        }
        total_resources: resources_aggregate {
          aggregate {
            count
          }
        }
      }
    }
    thread_models {
      id
      modelcatalog_configuration {
        id
        label
        description
        model_configuration_id
        software_version {
          id
          software {
            id
          }
        }
        inputs {
          input {
            id
            label
          }
        }
        outputs {
          output {
            id
            label
          }
        }
        parameters {
          parameter {
            id
            label
            has_default_value
            has_fixed_value
            has_minimum_accepted_value
            has_maximum_accepted_value
          }
        }
      }
      data_bindings {
        model_io {
          id
          name
        }
        dataslice_id
      }
      parameter_bindings {
        modelcatalog_parameter {
          id
          label
        }
        parameter_value
      }
    }
  }
}
