import { html, css, customElement } from 'lit-element';
import { PageViewElement } from '../../components/page-view-element';

import { SharedStyles } from '../../styles/shared-styles';
import { store, RootState } from '../../app/store';
import { connect } from 'pwa-helpers/connect-mixin';

import '../../components/nav-title'
import { db } from 'config/firebase';
import { Pathway, ExecutableEnsembleSummary } from 'screens/modeling/reducers';

import "weightless/tab-group";
import "weightless/tab";

@customElement("emulators-home")
export class EmulatorsHome extends connect(store)(PageViewElement) {

    static get styles() {
        return [
            css `
            @media (min-width: 1025px) {
                .content {
                    width: 75%;
                }
            }
            @media (max-width: 1024) {
                .content {
                    width: 100%;
                }
            }
            .content {
                margin: 0 auto;
            }
            ul li {
                padding: 10px;
            }
            `,
            SharedStyles
        ];
    }

    private _setVisibility(emulator, model) {
        let displaystyle = emulator == model ? "" : "none";
        this.shadowRoot.getElementById(emulator + "_emulators").style.display = displaystyle;
    }

    private _showEmulators(model) {
        this._setVisibility("pihm", model);
        this._setVisibility("topoflow", model);
        this._setVisibility("cycles", model);
        this._setVisibility("hand", model);
    }

    protected render() {
        let nav = [{label:'Model Products / Emulators', url:'emulators'}] 
        if(this._regionid == "ethiopia") {
            return html`
            <nav-title .nav="${nav}"></nav-title>

            <wl-tab-group align="center" style="width: 100%;">
                <wl-tab @click="${() => this._showEmulators('pihm')}" checked>PIHM</wl-tab>
                <wl-tab @click="${() => this._showEmulators('topoflow')}">TOPOFLOW</wl-tab>
                <wl-tab @click="${() => this._showEmulators('hand')}">HAND</wl-tab>
                <wl-tab @click="${() => this._showEmulators('cycles')}">CYCLES</wl-tab>
            </wl-tab-group>

            <div id="pihm_emulators" class="emulators">
                <h2>PIHM Emulators</h2>
                <table class="pure-table pure-table-bordered">
                    <thead>
                        <tr><th>Area</th><th>Region</th><th>Time period</th><th>Input (data preparation has been completed)</th><th>Model setup has been tested (outside MINT)</th><th>Setup (the model setup available in MINT)</th><th>Ensemble description (range of parameters completed in the simulation)</th><th>Output summary (Ensemble)</th><th>JSON-Summary (triggered manually)</th><th>URL to be shared (with hand-curated metadata and provenance)</th><th>Results reviewed by modeler</th><th>Quality</th><th>Status</th><th>Validated?</th><th>Usage Notes</th><th>Comments</th></tr>
                    </thead>
                    <tbody>
                        <tr><td>Baro (Oromia)</td><td>Oromia</td><td>2017</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-baro-gam-2c7bf2138d4fe78680310ca26e2614a4.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-baro-gam-2c7bf2138d4fe78680310ca26e2614a4.tgz</a></td><td>YES (WINGS)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-baro">https://w3id.org/okn/i/mint/pihm-v4.1.0-baro</a></td><td>Dates: 2017; PRCP (0.9,1,1.1); SFTMP (-1, 1,2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/WX6w5WG9syCkp6JhXyAL/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/WX6w5WG9syCkp6JhXyAL/results</a></td><td>n/a</td><td></td><td>Chris Duffy</td><td>1</td><td>Done (initial run to test model in region)</td><td>Yes</td><td>Model test run was successful</td></tr>
                        <tr><td>Baro (Oromia)</td><td>Oromia</td><td>2008-April2018</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-baro-gam-6bf82b55ecdeb2169b090fc124ef8117.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-baro-gam-6bf82b55ecdeb2169b090fc124ef8117.tgz</a></td><td>YES (WINGS)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-baro-full">https://w3id.org/okn/i/mint/pihm-v4.1.0-baro-full</a></td><td>Dates: 2000-2018; PRCP (0.9,1,1.1); ETP (0.8, 1, 1.2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/wbXTKQmFmEQuQOgMi9Ky/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/wbXTKQmFmEQuQOgMi9Ky/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/gwOa5pU7E7S4HLxc6i9Q_export/summary.json">https://ingestion.mint.isi.edu/data/gwOa5pU7E7S4HLxc6i9Q_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/PIHM/Baro-2000-2018.zip">https://data.mint.isi.edu/files/sharedResults/PIHM/Baro-2000-2018.zip</a></td><td>Chris Duffy</td><td>1-2</td><td>Completed</td><td>YES</td><td>The output of the model is valid after a spin-up phase. </td></tr>
                        <tr><td>Guder</td><td>Oromia</td><td>2017</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-guder-03e27a812e84d140a93667727bd0a4fd.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-guder-03e27a812e84d140a93667727bd0a4fd.tgz</a></td><td>YES (WINGS)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-guder">https://w3id.org/okn/i/mint/pihm-v4.1.0-guder</a></td><td>Dates: 2017; PRCP (0.9,1,1.1); SFTMP (-1, 1,2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/etZK2mpavnnjJRyfe5mm/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/etZK2mpavnnjJRyfe5mm/results</a></td><td>n/a</td><td></td><td>-Chris Duffy</td><td>1</td><td>Done (initial run to test model in region)</td><td>Yes</td><td>Model test run was successful</td></tr>
                        <tr><td>Guder</td><td>Oromia</td><td>2008-April2018</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-guder-213f016b3ecc76180f56c3c3f9cc7a0e.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-guder-213f016b3ecc76180f56c3c3f9cc7a0e.tgz</a></td><td>NO (not needed)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-guder-full">https://w3id.org/okn/i/mint/pihm-v4.1.0-guder-full</a></td><td>Dates: 2000-2018; PRCP (0.9,1,1.1); ETP (0.8, 1, 1.2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/DKn6afMctvVQhaOg0Y5Q/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/DKn6afMctvVQhaOg0Y5Q/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/DKn6afMctvVQhaOg0Y5Q_export/summary.json">https://ingestion.mint.isi.edu/data/DKn6afMctvVQhaOg0Y5Q_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/PIHM/Guder-2000-2018.zip">https://data.mint.isi.edu/files/sharedResults/PIHM/Guder-2000-2018.zip</a></td><td>Chris Duffy</td><td>2</td><td>Completed</td><td>Yes</td><td>The output of the model is valid after a spin-up phase</td></tr>
                        <tr><td>Muger</td><td>Oromia</td><td>2017</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-muger-11854a20dd2429e4bfa1d21419b47e67.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-muger-11854a20dd2429e4bfa1d21419b47e67.tgz</a></td><td>YES (WINGS)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-muger">https://w3id.org/okn/i/mint/pihm-v4.1.0-muger</a></td><td>Dates: 2017; PRCP (0.9,1,1.1); SFTMP (-1, 1,2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/1L4JMmK1MTmJJFquGFXB/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/1L4JMmK1MTmJJFquGFXB/results</a></td><td>n/a</td><td></td><td>-Chris Duffy</td><td>1</td><td>Done (initial run to test model in region)</td><td>Yes</td><td>Model test run was successful</td></tr>
                        <tr><td>Muger</td><td>Oromia</td><td>2008-April2018</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-muger-39eb0c043fa323ebcaa713e2eef654b0.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-muger-39eb0c043fa323ebcaa713e2eef654b0.tgz</a></td><td>NO (not needed)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-muger-full">https://w3id.org/okn/i/mint/pihm-v4.1.0-muger-full</a></td><td>Dates: 2000-2018; PRCP (0.9,1,1.1); ETP (0.8, 1, 1.2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/EniqL0YCVJPRJIF3IrgO/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/EniqL0YCVJPRJIF3IrgO/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/EniqL0YCVJPRJIF3IrgO_export/summary.json">https://ingestion.mint.isi.edu/data/EniqL0YCVJPRJIF3IrgO_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/PIHM/Muger-2000-2018.zip">https://data.mint.isi.edu/files/sharedResults/PIHM/Muger-2000-2018.zip</a></td><td>Chris Duffy</td><td>1-2</td><td>Completed</td><td>Yes</td><td>The output of the model is valid after a spin-up phase with some anomaous data.</td></tr>
                        <tr><td>Ganale</td><td>Oromia</td><td>2008-April2018</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-ganale-9c2c4a61aa5f685fc4821afb948d1214.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-ganale-9c2c4a61aa5f685fc4821afb948d1214.tgz</a></td><td>NO (not needed)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-ganale-full">https://w3id.org/okn/i/mint/pihm-v4.1.0-ganale-full</a></td><td>Dates: 2000-2018; PRCP (0.9,1,1.1); ETP (0.8, 1, 1.2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/5kIaza3ScBZwuVDkQtfc/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/5kIaza3ScBZwuVDkQtfc/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/5kIaza3ScBZwuVDkQtfc_export/summary.json">https://ingestion.mint.isi.edu/data/5kIaza3ScBZwuVDkQtfc_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/PIHM/Ganale-2000-2018.zip">https://data.mint.isi.edu/files/sharedResults/PIHM/Ganale-2000-2018.zip</a></td><td>Chris Duffy</td><td>1-2</td><td>Completed</td><td>Yes</td><td>The output of the model is valid after a spin-up phase with some anomalous data.</td></tr>
                        <tr><td>Jamma</td><td></td><td>2017</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-jamma-841383ade6ce27f51ecc4d7da1eae065.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-jamma-841383ade6ce27f51ecc4d7da1eae065.tgz</a></td><td>YES (WINGS)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-jamma">https://w3id.org/okn/i/mint/pihm-v4.1.0-jamma</a></td><td>Dates: 2017; PRCP (0.9,1,1.1); SFTMP (-1, 1,2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/VggqferoeUnXQB93yeBM/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/VggqferoeUnXQB93yeBM/results</a></td><td>n/a</td><td></td><td>Chris Duffy</td><td>1</td><td>Done (initial run to test model in region)</td><td>Yes</td><td>Model test run was successful</td></tr> 
                        <tr><td>Jamma</td><td></td><td>2008-April2018</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-jamma-743327e83e8db47a55f1c3ab1db65462.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-jamma-743327e83e8db47a55f1c3ab1db65462.tgz</a></td><td>NO (not needed)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-jamma-full">https://w3id.org/okn/i/mint/pihm-v4.1.0-jamma-full</a></td><td>Dates: 2000-2018; PRCP (0.9,1,1.1); ETP (0.8, 1, 1.2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/7yzeCTrH9z0Y0fAIiGsT/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/7yzeCTrH9z0Y0fAIiGsT/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/7yzeCTrH9z0Y0fAIiGsT_export/summary.json">https://ingestion.mint.isi.edu/data/7yzeCTrH9z0Y0fAIiGsT_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/PIHM/Jamma-2000-2018.zip">https://data.mint.isi.edu/files/sharedResults/PIHM/Jamma-2000-2018.zip</a></td><td>Chris Duffy</td><td>1-2</td><td>Completed</td><td>Yes</td><td>The output of the model is valid after a spin-up phase with some anomaous data.</td></tr>
                        <tr><td>Bashilo</td><td></td><td>2017</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-bashilo-670ec7019c625ee04ee56e38e7fb047c.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-bashilo-670ec7019c625ee04ee56e38e7fb047c.tgz</a></td><td>YES (WINGS)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-bashilo">https://w3id.org/okn/i/mint/pihm-v4.1.0-bashilo</a></td><td>Dates: 2017; PRCP (0.9,1,1.1); SFTMP (-1, 1,2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/l3EAhLLCUv2NtFbYVLkp/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/l3EAhLLCUv2NtFbYVLkp/results</a></td><td>n/a</td><td></td><td>Chris Duffy</td><td>1</td><td>Done (initial run to test model in region)</td><td>Yes</td><td>Model test run was successful</td></tr>
                        <tr><td>Bashilo</td><td></td><td>2008-April2018</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-bashilo-f7766968423b8f66c5b9264e819f2733.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-bashilo-f7766968423b8f66c5b9264e819f2733.tgz</a></td><td>NO (not needed)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-bashilo-full">https://w3id.org/okn/i/mint/pihm-v4.1.0-bashilo-full</a></td><td>Dates: 2000-2018; PRCP (0.9,1,1.1); ETP (0.8, 1, 1.2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/VFtUYdyUqcO91MrvGq21/models">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/VFtUYdyUqcO91MrvGq21/models</a></td><td><a href="https://ingestion.mint.isi.edu/data/VFtUYdyUqcO91MrvGq21_export/summary.json">https://ingestion.mint.isi.edu/data/VFtUYdyUqcO91MrvGq21_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/PIHM/Bashilo-2000-2018.zip">https://data.mint.isi.edu/files/sharedResults/PIHM/Bashilo-2000-2018.zip</a></td><td>Chris Duffy</td><td>1-2</td><td>Completed</td><td>Yes</td><td>The output of the model is valid after a spin-up phase with some anomaous data.</td></tr>
                        <tr><td>Beko-Tippi</td><td></td><td>2017</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-beko-tippi-a973531b118289dbe142df07be5130ee.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-beko-tippi-a973531b118289dbe142df07be5130ee.tgz</a></td><td>YES (WINGS)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-beko-tippi">https://w3id.org/okn/i/mint/pihm-v4.1.0-beko-tippi</a></td><td>Dates: 2017; PRCP (0.9,1,1.1); SFTMP (-1, 1,2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/PvjIvVMa4ELIQQcDYgIM/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h/PvjIvVMa4ELIQQcDYgIM/results</a></td><td>n/a</td><td></td><td>Chris Duffy</td><td>1</td><td>Done (initial run to test model in region)</td><td>Yes</td><td>Model test run was successful</td></tr>
                        <tr><td>Beko-Tippi</td><td></td><td>2008-April2018</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-beko-tippi-b55168b7f67ef454ed4013ffe2a4b1ea.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-beko-tippi-b55168b7f67ef454ed4013ffe2a4b1ea.tgz</a></td><td>NO (not needed)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-beko-tippi-full">https://w3id.org/okn/i/mint/pihm-v4.1.0-beko-tippi-full</a></td><td>Dates: 2000-2018; PRCP (0.9,1,1.1); ETP (0.8, 1, 1.2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/pCygfd0EDyH6uZ4WL28h/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/pCygfd0EDyH6uZ4WL28h/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/pCygfd0EDyH6uZ4WL28h_export/summary.json">https://ingestion.mint.isi.edu/data/pCygfd0EDyH6uZ4WL28h_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/PIHM/Beko-Tippi-2000-2018.zip">https://data.mint.isi.edu/files/sharedResults/PIHM/Beko-Tippi-2000-2018.zip</a></td><td>Chris Duffy</td><td>1-2</td><td>Completed</td><td>Yes</td><td>The output of the model is valid after a spin-up phase with some anomaous data.</td></tr>
                        <tr><td>Tekeze</td><td></td><td>2008-April2018</td><td><a href="https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-tekeze-dam-832df7185e048ad6fcad9aa6a3c82f8b.tgz">https://data.mint.isi.edu/files/wings-dev/mint/mint-test/data/pihm-input-tekeze-dam-832df7185e048ad6fcad9aa6a3c82f8b.tgz</a></td><td>NO (not needed)</td><td><a href="https://w3id.org/okn/i/mint/pihm-v4.1.0-tekeze-full">https://w3id.org/okn/i/mint/pihm-v4.1.0-tekeze-full</a></td><td>Dates: 2000-2018; PRCP (0.9,1,1.1); ETP (0.8, 1, 1.2)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/dRBdVH6uD7P2izq5BFeu/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/t6QkONfwbFhUl86NOwT3/dRBdVH6uD7P2izq5BFeu/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/TDfPujmXbubkbLTeF42a_export/summary.json">https://ingestion.mint.isi.edu/data/TDfPujmXbubkbLTeF42a_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/PIHM/Tekeze-2000-2018.zip">https://data.mint.isi.edu/files/sharedResults/PIHM/Tekeze-2000-2018.zip</a></td><td>Chris Duffy</td><td></td><td>Completed</td><td>Yes</td><td>The output of the model is valid after a spin-up phase with some anomaous data.</td></tr>
                    </tbody>
                </table>
            </div>

            <div id="topoflow_emulators" style="display:none" class="emulators">
                <h2>TOPOFLOW Emulators</h2>
                <table class="pure-table pure-table-bordered">
                    <thead>
                        <tr><th>Area</th><th>Region</th><th>Time period</th><th>Input (data preparation has been completed)</th><th>Model setup has been tested (outside MINT)</th><th>Setup (the model setup available in MINT)</th><th>Ensemble description (range of parameters completed in the simulation)</th><th>Output summary (Ensemble)</th><th>JSON-Summary (triggered manually)</th><th>URL to be shared (with hand-curated metadata and provenance)</th><th>Results reviewed by modeler</th><th>Status</th><th>Validated?</th><th>Usage Notes</th><th>Comments</th></tr>
                    </thead>
                    <tbody>
                        <tr><td>Baro (Oromia)</td><td>Oromia</td><td>2008 (gpm)</td><td>Config: <a href="https://github.com/mintproject/MINT-WorkflowDomain/raw/master/WINGSWorkflowComponents/topoflow-36/data/Baro_Gam_1min_Input.zip Precip rates: https://publisher.mint.isi.edu/ognUm/topoflow_gpm_2018_baro_15quantile.tar.gz">https://github.com/mintproject/MINT-WorkflowDomain/raw/master/WINGSWorkflowComponents/topoflow-36/data/Baro_Gam_1min_Input.zip Precip rates: https://publisher.mint.isi.edu/ognUm/topoflow_gpm_2018_baro_15quantile.tar.gz</a></td><td>Yes (Node 1)</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_simple_Baro">https://w3id.org/okn/i/mint/topoflow_cfg_simple_Baro</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/s8WAHXQKYliYbP90ntzn/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/s8WAHXQKYliYbP90ntzn/results</a></td><td>-</td><td></td><td>-</td><td>Finished. Any adjustable parameters to tune? (Scott)</td><td>NO
                        <tr><td>Baro (variable precip rates)</td><td>Oromia</td><td>2018 (Forecast)</td>
                            <td>- Config: <a href="https://github.com/mintproject/MINT-WorkflowDomain/raw/master/WINGSWorkflowComponents/topoflow-36/data/Baro_Gam_1min_Input.zip">https://github.com/mintproject/MINT-WorkflowDomain/raw/master/WINGSWorkflowComponents/topoflow-36/data/Baro_Gam_1min_Input.zip</a>
                        - Data catalog ids: 
                        https://dev.mint.isi.edu/ethiopia/datasets/browse/bf5bf384-768e-4037-b7ff-08169869dd24/xTESsM6UaTIAfckPVWbs
                        https://dev.mint.isi.edu/ethiopia/datasets/browse/74e99ea2-235b-4994-a136-1fec22b21849/xTESsM6UaTIAfckPVWbs
                        https://dev.mint.isi.edu/ethiopia/datasets/browse/297b7d16-d2ca-407a-aec7-26db3ec480fa/xTESsM6UaTIAfckPVWbs
                        https://dev.mint.isi.edu/ethiopia/datasets/browse/15799674-a408-4e18-be93-184c04e8ba93/xTESsM6UaTIAfckPVWbs
                        <a href="https://dev.mint.isi.edu/ethiopia/datasets/browse/7cc01424-da6a-4639-bcf3-21e73aa9d564/xTESsM6UaTIAfckPVWbs"">https://dev.mint.isi.edu/ethiopia/datasets/browse/7cc01424-da6a-4639-bcf3-21e73aa9d564/xTESsM6UaTIAfckPVWbs"</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Baro">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Baro</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/l8uffgtNXqCRexz76puM/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/l8uffgtNXqCRexz76puM/results</a></td><td>-</td><td></td><td>-</td><td>Finished. Any adjustable parameters to tune? (Scott)</td><td>NO
                        <tr><td>Baro (GPM)</td><td>Oromia</td><td>2008-April2018</td><td>"- Config: https://github.com/mintproject/MINT-WorkflowDomain/raw/master/WINGSWorkflowComponents/topoflow-36/data/Baro_Gam_1min_Input.zip 
                        <tr><td>- Data catalog ids: <a href="https://dev.mint.isi.edu/ethiopia/datasets/browse/a3cea308-7e80-4136-b669-abcbf1d14b10/ethiopia"">https://dev.mint.isi.edu/ethiopia/datasets/browse/a3cea308-7e80-4136-b669-abcbf1d14b10/ethiopia"</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Baro ">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Baro </a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/EvdhYtTJ42aS8BaZ2yGS/runs">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/EvdhYtTJ42aS8BaZ2yGS/runs</a></td><td><a href="https://ingestion.mint.isi.edu/data/EvdhYtTJ42aS8BaZ2yGS_export/summary.json">https://ingestion.mint.isi.edu/data/EvdhYtTJ42aS8BaZ2yGS_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Baro/GPM.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Baro/GPM.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>Baro (GLDAS)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Guder_30sec.zip - Precipitation rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/6def2f0c-4077-40d2-ac16-4ecbcf3a57ce/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Guder_30sec.zip - Precipitation rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/6def2f0c-4077-40d2-ac16-4ecbcf3a57ce/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Baro">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Baro</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/zhprlchxCS092iaddiyD/datasets">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/zhprlchxCS092iaddiyD/datasets</a></td><td><a href="https://ingestion.mint.isi.edu/data/UO9HCLXgdFaJPuJtuRHG_export/summary.json">https://ingestion.mint.isi.edu/data/UO9HCLXgdFaJPuJtuRHG_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Baro/GLDAS.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Baro/GLDAS.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>Guder</td><td>Oromia</td><td>2008 (gpm)</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Guder_30sec.zip, Precip rates: https://data.mint.isi.edu/files/topoflow-regions/regions/inputs%20rates/guder_gpm_2008_30_agg.tar.gz">https://data.mint.isi.edu/files/topoflow-regions/regions/Guder_30sec.zip, Precip rates: https://data.mint.isi.edu/files/topoflow-regions/regions/inputs%20rates/guder_gpm_2008_30_agg.tar.gz</a></td><td>Yes (Node 1)</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_simple_Guder">https://w3id.org/okn/i/mint/topoflow_cfg_simple_Guder</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/sK53rJ9YTm8fiOQ1QVeF/runs">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/sK53rJ9YTm8fiOQ1QVeF/runs</a></td><td>-</td><td></td><td>-</td><td>Finished. Any knobs to tune? (Scott)</td></tr>
                        <tr><td>Guder (GPM)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Guder_30sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/0113a9dd-0a1a-442c-8cbb-49950d8c6ab3/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Guder_30sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/0113a9dd-0a1a-442c-8cbb-49950d8c6ab3/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Guder">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Guder</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/jzZVBuCmAEvzAcWY2SQ9">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/jzZVBuCmAEvzAcWY2SQ9</a></td><td><a href="https://ingestion.mint.isi.edu/data/jzZVBuCmAEvzAcWY2SQ9_export/summary.json">https://ingestion.mint.isi.edu/data/jzZVBuCmAEvzAcWY2SQ9_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Guder/GPM.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Guder/GPM.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>Guder (GLDAS)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Guder_30sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/25be6bc5-7a7a-4d03-a8f5-faca98158f2a/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Guder_30sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/25be6bc5-7a7a-4d03-a8f5-faca98158f2a/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Guder">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Guder</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/Fom5dKxfMy8CxTnBMWhc">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/Fom5dKxfMy8CxTnBMWhc</a></td><td><a href="https://ingestion.mint.isi.edu/data/Fom5dKxfMy8CxTnBMWhc_export/summary.json">https://ingestion.mint.isi.edu/data/Fom5dKxfMy8CxTnBMWhc_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Guder/GLDAS.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Guder/GLDAS.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>Muger</td><td>Oromia</td><td>2008 (gpm)</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Muger_30sec.zip; Precip rates: https://data.mint.isi.edu/files/topoflow-regions/regions/inputs%20rates/muger_gpm_2008_30_agg.tar.gz">https://data.mint.isi.edu/files/topoflow-regions/regions/Muger_30sec.zip; Precip rates: https://data.mint.isi.edu/files/topoflow-regions/regions/inputs%20rates/muger_gpm_2008_30_agg.tar.gz</a></td><td>Yes (Node 1)</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_simple_Muger">https://w3id.org/okn/i/mint/topoflow_cfg_simple_Muger</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/wjY9dLJbaw9GZttEtPKC/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/wjY9dLJbaw9GZttEtPKC/results</a></td><td>-</td><td></td><td>-</td><td>Finished. Any knobs to tune? (Scott)</td><td>NO
                        <tr><td>Muger (GPM)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Muger_30sec.zip  - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/4d325edd-78e3-4b85-9d5c-67538f4ccbd0/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Muger_30sec.zip  - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/4d325edd-78e3-4b85-9d5c-67538f4ccbd0/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Muger">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Muger</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/kwbvC3XpzUOPDQvYQWCe">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/kwbvC3XpzUOPDQvYQWCe</a></td><td><a href="https://ingestion.mint.isi.edu/data/kwbvC3XpzUOPDQvYQWCe_export/summary.json">https://ingestion.mint.isi.edu/data/kwbvC3XpzUOPDQvYQWCe_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Muger/GPM.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Muger/GPM.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>Muger (GLDAS)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Muger_30sec.zip  - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/5cdfcc63-a9ba-46b4-9bee-fd16ee877936/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Muger_30sec.zip  - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/5cdfcc63-a9ba-46b4-9bee-fd16ee877936/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Muger">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Muger</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/gLqZyf3pwYhQBV8NZRGy">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/gLqZyf3pwYhQBV8NZRGy</a></td><td><a href="https://ingestion.mint.isi.edu/data/gLqZyf3pwYhQBV8NZRGy_export/summary.json">https://ingestion.mint.isi.edu/data/gLqZyf3pwYhQBV8NZRGy_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Muger/GLDAS.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Muger/GLDAS.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>Awash</td><td>Oromia</td><td>2008 (gpm)</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Awash-border_60sec.zip; Precip rates: https://data.mint.isi.edu/files/topoflow-regions/regions/inputs%20rates/awash_gpm_2008_60_agg.tar.gz">https://data.mint.isi.edu/files/topoflow-regions/regions/Awash-border_60sec.zip; Precip rates: https://data.mint.isi.edu/files/topoflow-regions/regions/inputs%20rates/awash_gpm_2008_60_agg.tar.gz</a></td><td>Yes (Node 1)</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_simple_Awash">https://w3id.org/okn/i/mint/topoflow_cfg_simple_Awash</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/D1epX6cfdmGOyVCh0cab/runs">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/D1epX6cfdmGOyVCh0cab/runs</a></td><td>-</td><td></td><td>-</td><td>Finished. Any knobs to tune? (Scott)</td><td>NO
                        <tr><td>Awash (GPM)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Awash-border_60sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/8ac790e4-820e-490b-ba66-ee6071ac6104/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Awash-border_60sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/8ac790e4-820e-490b-ba66-ee6071ac6104/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Awash">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Awash</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/LN1z7b6IyXDGVGD6PTGH/runs">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/LN1z7b6IyXDGVGD6PTGH/runs</a></td><td><a href="https://ingestion.mint.isi.edu/data/LN1z7b6IyXDGVGD6PTGH_export/summary.json">https://ingestion.mint.isi.edu/data/LN1z7b6IyXDGVGD6PTGH_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Awash/GPM.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Awash/GPM.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>Awash (GLDAS)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Awash-border_60sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/d818bd9d-28ce-4720-b313-7de67dcf5c71/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Awash-border_60sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/d818bd9d-28ce-4720-b313-7de67dcf5c71/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Awash">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Awash</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/FXzkyMuZhI9No7LMOLUP">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/FXzkyMuZhI9No7LMOLUP</a></td><td><a href="https://ingestion.mint.isi.edu/data/FXzkyMuZhI9No7LMOLUP_export/summary.json">https://ingestion.mint.isi.edu/data/FXzkyMuZhI9No7LMOLUP_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Awash/GLDAS.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Awash/GLDAS.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>Shebelle</td><td>Oromia</td><td>2008 (gpm)</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Shebelle-Imi_60sec.zip; Precip rates: https://data.mint.isi.edu/files/topoflow-regions/regions/inputs%20rates/shebelle_gpm_2008_30_agg.tar.gz">https://data.mint.isi.edu/files/topoflow-regions/regions/Shebelle-Imi_60sec.zip; Precip rates: https://data.mint.isi.edu/files/topoflow-regions/regions/inputs%20rates/shebelle_gpm_2008_30_agg.tar.gz</a></td><td>Yes (Node 1)</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_simple_Shebelle">https://w3id.org/okn/i/mint/topoflow_cfg_simple_Shebelle</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/2kIRPrHCTMS9xEtkg9Kw/runs">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/2kIRPrHCTMS9xEtkg9Kw/runs</a></td><td>-</td><td></td><td>-</td><td>Finished. Any knobs to tune? (Scott)</td><td>NO
                        <tr><td>Shebelle (GPM)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Shebelle-Imi_60sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/079c1109-01d3-41c2-8798-94cbda23cfe4/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Shebelle-Imi_60sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/079c1109-01d3-41c2-8798-94cbda23cfe4/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Shebelle">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Shebelle</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/qE1FKGKW1rpAFcyEEJKH/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/qE1FKGKW1rpAFcyEEJKH/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/qE1FKGKW1rpAFcyEEJKH_export/summary.json">https://ingestion.mint.isi.edu/data/qE1FKGKW1rpAFcyEEJKH_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Shebelle/GPM.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Shebelle/GPM.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>Shebelle (GLDAS)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Shebelle-Imi_60sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/8450a29b-086a-4734-a8d6-b7286726db9a/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Shebelle-Imi_60sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/8450a29b-086a-4734-a8d6-b7286726db9a/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Shebelle">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Shebelle</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/g5mtBcfanvdguHqTHwDS/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/g5mtBcfanvdguHqTHwDS/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/g5mtBcfanvdguHqTHwDS_export/summary.json">https://ingestion.mint.isi.edu/data/g5mtBcfanvdguHqTHwDS_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Shebelle/GLDAS.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Shebelle/GLDAS.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>"Ganale
                        <tr><td>"</td><td>Oromia</td><td>2008 (gpm)</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Ganale-border_60sec.zip; Precip rates: https://data.mint.isi.edu/files/topoflow-regions/regions/inputs%20rates/ganale_gpm_2008_60_agg.tar.gz ">https://data.mint.isi.edu/files/topoflow-regions/regions/Ganale-border_60sec.zip; Precip rates: https://data.mint.isi.edu/files/topoflow-regions/regions/inputs%20rates/ganale_gpm_2008_60_agg.tar.gz </a></td><td>Yes (Node 1)</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_simple_Ganale">https://w3id.org/okn/i/mint/topoflow_cfg_simple_Ganale</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/zbMpzCAsnNJFNDZSgoJS/runs">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/4ssRI03e5lNjN2VLuCoa/zbMpzCAsnNJFNDZSgoJS/runs</a></td><td>-</td><td></td><td>-</td><td>Finished. Any knobs to tune? (Scott)</td><td>NO
                        <tr><td>Ganale (GPM)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Ganale-border_60sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/5f0efdb1-0057-423c-aa6e-90518390d3b3/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Ganale-border_60sec.zip - Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/5f0efdb1-0057-423c-aa6e-90518390d3b3/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Ganale">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Ganale</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/mBvSXIOK4AMcXMpuLrFv">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/mBvSXIOK4AMcXMpuLrFv</a></td><td><a href="https://ingestion.mint.isi.edu/data/mBvSXIOK4AMcXMpuLrFv_export/summary.json">https://ingestion.mint.isi.edu/data/mBvSXIOK4AMcXMpuLrFv_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Ganale/GPM.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Ganale/GPM.zip</a></td><td>-</td><td>Completed</td></tr>
                        <tr><td>Ganale (GLDAS)</td><td>Oromia</td><td>2008-April2018</td><td>Config: <a href="https://data.mint.isi.edu/files/topoflow-regions/regions/Ganale-border_60sec.zip -Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/06cc80e2-ad97-4c26-965f-04c8ac134809/ethiopia">https://data.mint.isi.edu/files/topoflow-regions/regions/Ganale-border_60sec.zip -Precip rates: https://dev.mint.isi.edu/ethiopia/datasets/browse/06cc80e2-ad97-4c26-965f-04c8ac134809/ethiopia</a></td><td>No</td><td><a href="https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Ganale">https://w3id.org/okn/i/mint/topoflow_cfg_advanced_Ganale</a></td><td>N/A (no knobs)</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/1beCAUFWxJe5WD1wZkIw/models">https://dev.mint.isi.edu/ethiopia/modeling/scenario/vol641Tb5Ku9xfI0tC2Q/T6eVSQodyolTmN8x7CAg/1beCAUFWxJe5WD1wZkIw/models</a></td><td><a href="https://ingestion.mint.isi.edu/data/1beCAUFWxJe5WD1wZkIw_export/summary.json">https://ingestion.mint.isi.edu/data/1beCAUFWxJe5WD1wZkIw_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/Topoflow/Ganale/GLDAS.zip">https://data.mint.isi.edu/files/sharedResults/Topoflow/Ganale/GLDAS.zip</a></td><td>-</td><td>Completed</td></tr>
                    </tbody>
                </table>
            </div>

            <div id="hand_emulators" style="display:none" class="emulators">
                <h2>HAND Emulators</h2>
                <table class="pure-table pure-table-bordered">
                    <thead>
                        <tr><th>Area</th><th>Region</th><th>Time period</th><th>Input (data preparation has been completed)</th><th>Model setup has been tested (outside MINT)</th><th>Setup (the model setup available in MINT)</th><th>Ensemble description (range of parameters completed in the simulation)</th><th>Output summary (Ensemble)</th><th>JSON-Summary (triggered manually)</th><th>URL to be shared (with hand-curated metadata and provenance)</th><th>Results reviewed by modeler</th><th>Status</th><th>Validated?</th><th>Usage Notes</th><th>Comments</th></tr>
                    </thead>
                    <tbody>
                        <tr><td>Baro </td><td>Oromia</td><td>N/A</td><td><a href="https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Baro/Baro_DEM_buffer.tif">https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Baro/Baro_DEM_buffer.tif</a></td><td>Yes (Node 1)</td><td>"<a href="https://w3id.org/okn/i/mint/hand_v1_simple_baro"">https://w3id.org/okn/i/mint/hand_v1_simple_baro"</a></td><td>Threshold: 22.3</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/zeb8nvpXeiQ5sQVxKt4I">https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/zeb8nvpXeiQ5sQVxKt4I</a></td><td><a href="https://ingestion.mint.isi.edu/data/zeb8nvpXeiQ5sQVxKt4I_export/summary.json">https://ingestion.mint.isi.edu/data/zeb8nvpXeiQ5sQVxKt4I_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/HAND/Baro.zip">https://data.mint.isi.edu/files/sharedResults/HAND/Baro.zip</a></td><td>-</td><td>Results Ok. To be validated </td><td>NO</td><td>Note: Not latest version</td></tr>
                        <tr><td>Guder</td><td>Oromia</td><td>N/A</td><td><a href="https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Guder/Guder_DEM_buffer.tif">https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Guder/Guder_DEM_buffer.tif</a></td><td>Yes (Node 1)</td><td>"<a href="https://w3id.org/okn/i/mint/hand_v1_simple_guder"">https://w3id.org/okn/i/mint/hand_v1_simple_guder"</a></td><td>Threshold: 22.3</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/pPv1ncjpuJ3cFi4neccF/runs">https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/pPv1ncjpuJ3cFi4neccF/runs</a></td><td><a href="https://ingestion.mint.isi.edu/data/pPv1ncjpuJ3cFi4neccF_export/summary.json">https://ingestion.mint.isi.edu/data/pPv1ncjpuJ3cFi4neccF_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/HAND/Guder.zip">https://data.mint.isi.edu/files/sharedResults/HAND/Guder.zip</a></td><td>-</td><td>Results Ok. To be validated </td><td>NO</td><td>Note: Not latest version</td></tr>
                        <tr><td>Muger</td><td>Oromia</td><td>N/A</td><td><a href="https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Muger/Muger_DEM_buffer.tif">https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Muger/Muger_DEM_buffer.tif</a></td><td>Yes (Node 1)</td><td>"<a href="https://w3id.org/okn/i/mint/hand_v1_simple_muger"">https://w3id.org/okn/i/mint/hand_v1_simple_muger"</a></td><td>Threshold: 22.3</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/je9iWYBhpntcTsPcigXB/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/je9iWYBhpntcTsPcigXB/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/je9iWYBhpntcTsPcigXB_export/summary.json">https://ingestion.mint.isi.edu/data/je9iWYBhpntcTsPcigXB_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/HAND/Muger.zip">https://data.mint.isi.edu/files/sharedResults/HAND/Muger.zip</a></td><td>-</td><td>Results Ok. To be validated </td><td>NO</td><td>Note: Not latest version</td></tr>
                        <tr><td>Awash</td><td>Oromia</td><td>N/A</td><td><a href="https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Awash/Awash-border_DEM_buffer.tif">https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Awash/Awash-border_DEM_buffer.tif</a></td><td>Yes (Node 1)</td><td>"<a href="https://w3id.org/okn/i/mint/hand_v1_simple_awash"">https://w3id.org/okn/i/mint/hand_v1_simple_awash"</a></td><td>Threshold: 22.3</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/q5v983pi0SHXyHG8lY3Y">https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/q5v983pi0SHXyHG8lY3Y</a></td><td><a href="https://ingestion.mint.isi.edu/data/sUC7yyNkovWW6ajR3fg5_export/summary.json">https://ingestion.mint.isi.edu/data/sUC7yyNkovWW6ajR3fg5_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/HAND/Awash.zip">https://data.mint.isi.edu/files/sharedResults/HAND/Awash.zip</a></td><td>-</td><td>Results Ok. To be validated </td><td>NO</td><td>Note: Not latest version</td></tr>
                        <tr><td>Shebelle</td><td>Oromia</td><td>N/A</td><td><a href="https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Shebelle/Shebelle-Imi_3sec_DEM_buffer.tif">https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Shebelle/Shebelle-Imi_3sec_DEM_buffer.tif</a></td><td>Yes (Node 1)</td><td>"<a href="https://w3id.org/okn/i/mint/hand_v1_simple_shebelle"">https://w3id.org/okn/i/mint/hand_v1_simple_shebelle"</a></td><td>Threshold: 22.3</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/sUC7yyNkovWW6ajR3fg5">https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/sUC7yyNkovWW6ajR3fg5</a></td><td><a href="https://ingestion.mint.isi.edu/data/q5v983pi0SHXyHG8lY3Y_export/summary.json">https://ingestion.mint.isi.edu/data/q5v983pi0SHXyHG8lY3Y_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/HAND/Shebelle.zip">https://data.mint.isi.edu/files/sharedResults/HAND/Shebelle.zip</a></td><td>-</td><td>Results Ok. To be validated </td><td>NO</td><td>Note: Not latest version</td></tr>
                        <tr><td>Ganale</td><td>Oromia</td><td>N/A</td><td><a href="https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Ganale/Ganale-border_3sec_DEM_buffer.tif">https://data.mint.isi.edu/files/hand-dem/GIS-Oromia/Ganale/Ganale-border_3sec_DEM_buffer.tif</a></td><td>Yes (Node 1). </td><td>"<a href="https://w3id.org/okn/i/mint/hand_v1_simple_ganale"">https://w3id.org/okn/i/mint/hand_v1_simple_ganale"</a></td><td>Threshold: 22.3</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/uZWdcJMRjwmVm8FdIU7i/results">https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/uZWdcJMRjwmVm8FdIU7i/results</a></td><td><a href="https://ingestion.mint.isi.edu/data/uZWdcJMRjwmVm8FdIU7i_export/summary.json">https://ingestion.mint.isi.edu/data/uZWdcJMRjwmVm8FdIU7i_export/summary.json</a></td><td><a href="https://data.mint.isi.edu/files/sharedResults/HAND/Ganale.zip">https://data.mint.isi.edu/files/sharedResults/HAND/Ganale.zip</a></td><td>-</td><td>Results Ok. To be validated </td><td>NO</td><td>Note: Not latest version</td></tr>
                        <tr><td>Jamma</td><td></td><td>N/A</td><td><a href="https://data.mint.isi.edu/files/hand-dem/Jamma_DEM.tif">https://data.mint.isi.edu/files/hand-dem/Jamma_DEM.tif</a></td><td>Yes (Node 1)</td><td>"<a href="https://w3id.org/okn/i/mint/hand_v1_simple_jamma"">https://w3id.org/okn/i/mint/hand_v1_simple_jamma"</a></td><td>Threshold: 22.3</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/fNNs1aPlHsl3P1EhM5Ge">https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/fNNs1aPlHsl3P1EhM5Ge</a></td><td></td><td></td><td>-</td><td>Results Ok. To be validated </td><td>NO</td><td>Note: Not latest version</td></tr>
                        <tr><td>Bashilo</td><td></td><td>N/A</td><td><a href="https://data.mint.isi.edu/files/hand-dem/Bashilo_DEM.tif">https://data.mint.isi.edu/files/hand-dem/Bashilo_DEM.tif</a></td><td>Yes (Node 1)</td><td>"<a href="https://w3id.org/okn/i/mint/hand_v1_simple_bashilo"">https://w3id.org/okn/i/mint/hand_v1_simple_bashilo"</a></td><td>Threshold: 22.3</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/Y9ffZCpgHSL2Zq3v29T5">https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/Y9ffZCpgHSL2Zq3v29T5</a></td><td></td><td></td><td>-</td><td>Results Ok. To be validated </td><td>NO</td><td>Note: Not latest version</td></tr>
                        <tr><td>Beko-Tippi</td><td></td><td>N/A</td><td><a href="https://data.mint.isi.edu/files/hand-dem/Beko-Tippi_DEM.tif">https://data.mint.isi.edu/files/hand-dem/Beko-Tippi_DEM.tif</a></td><td>Yes (Node 1)</td><td>"<a href="https://w3id.org/okn/i/mint/hand_v1_simple_beko-tippi"">https://w3id.org/okn/i/mint/hand_v1_simple_beko-tippi"</a></td><td>Threshold: 22.3</td><td><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/Tc0T2c7KcZ6v49Prm4vB/runs">https://dev.mint.isi.edu/ethiopia/modeling/scenario/EnaNTF1qst06U4STDl78/dAkQZmVskdPUcCkk7gAg/Tc0T2c7KcZ6v49Prm4vB/runs</a></td><td></td><td></td><td>-</td><td>Results Ok. To be validated </td><td>NO</td><td>Note: Not latest version</td></tr>                    
                    </tbody>
                </table>
            </div>

            <div id="cycles_emulators" style="display:none" class="emulators">
                <h2>CYCLES Emulators</h2>
                <table class="pure-table pure-table-bordered">
                    <thead>
                        <tr><th>Region</th><th>Time period</th><th>Input (data preparation has been completed)</th><th>Model setup has been tested (outside MINT)</th><th>Setup (the model setup available in MINT)</th><th>Ensemble description (range of parameters completed in the simulation)</th><th>Output summary (Ensemble)</th><th>Results reviewed by modeler</th><th>Quality</th><th>Status</th><th>Validated?</th><th>Comments</th></tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
                <ul>
                    <li>
                        <h3>CYCLES</h3>
                        <ul>
                            <li>Gambela: <a href="https://data.mint.isi.edu/files/simulation-runs/cycles/summary/ethiopia/gambela/"
                                >https://data.mint.isi.edu/files/simulation-runs/cycles/summary/ethiopia/gambela/</a></li>
                            <li>Region/area: All GLDAS grids at 0.5 degree resolution within South Sudan and Gambela, Ethiopia 
                            (about 55 x 55 km grids at these latitudes).</li>
                            <li>Model version: Cycles v0.9.4-alpha</li>
                            <li>Config: Look at CSV File of simulation matrix. Soil data are from ISRIC, and 
                            meteorological forcing data are from GLDAS.</li>
                            <li>Years: 2000-2017</li>
                            <li>Crops South Sudan: Maize, sorghum, sesame, peanuts</li>
                            <li>Crops Ethiopia - Gambella region: Maize, sorghum, sesame (but only applicable to highland). </li>
                            <li># Multiple variables being varied simultaneously</li>
                        </ul>
                        The runs from Cycles report the simulated yield of different crops taking into account soil conditions, 
                        cropping sequence, management practice, weed pressure, and local weather. The simulation results can be 
                        mapped to any cropland that is within the GLDAS grid. 
                        <ul>
                            <li>
                                The Cycles agricultural model was run for Oromia for 2000 to 2017
                                <ul>
                                    <li>
                                        <a href="/ethiopia/modeling/scenario/vCwen8MUT3jgza4A8vq4/ywYH9PGRKJZoQLpqp3RH/ZoluO9Idrkile3f6SZ31/results">Cycles for Oromia (90720 runs)</a>
                                    </li>
                                </ul>
                            </li>   
                        </ul>
                    </li>
                </ul>                
            </div>


            <ul>
                <li>
                    <h3>PIHM</h3>
                    <ul>
                        <li>File names contain region and metadata in uncompressed files for basins  Muger, Beko-Tippi, Jamma, 
                        Baro, Guder, Bashilo. The simulation period is for 2017 only</li>
                        <li>Vary one variable at a time as normal, high, low Look at CSV File of sensitivity matrix included. 
                        The variables included are precipitation and temperature.</li>
                        <li>See CSV File of sensitivity matrix <a href="https://data.mint.isi.edu/files/simulation-runs/pihm/"
                            >https://data.mint.isi.edu/files/simulation-runs/pihm/</li>
                        <li># The atmospheric data uses GLDAS, 2017 daily data, 
                            all other spatial data is specified located in MINT data catalog.</li>
                        <li>Visualization of Surface Flooding Index spatial map  (monthly 2017) and a Streamflow duration Index 
                            are the basic outputs. However streamflow simulations for all points in each watershed are also available.</li>
                        <li><a href="https://dev.mint.isi.edu/ethiopia/modeling/scenario/hcbtnXF5gRSnUIszeEcI/VFVlWwqUOOpG3PYFko0h"
                            >UI link to outputs for configuration of each model run in Ethiopia</a></li>
                        <li>All PIHM test model runs are available here: <a href="https://data.mint.isi.edu/files/simulation-runs/pihm/test-runs/"
                            >https://data.mint.isi.edu/files/simulation-runs/pihm/test-runs/</a>
                            <ul>
                                File Descriptions:
                                <li>GLDAS 2017 Baseline - pihm-output-ethiopia-8884b6867b19b9e9079c5af01ef47dca.tgz</li>
                                <li>GLDAS 2017 TS_PRCP 1.1 - pihm-output-ethiopia-793616808ff9e6de7a1339b82766b72e.tgz</li>
                                <li>GLDAS 2017 TS_PRCP 0.9 - pihm-output-ethiopia-b6995862016115dc8f3e55692adb6b7b.tgz</li>
                                <li>FLDAS 2017 Baseline - pihm-output-ethiopia-25db3224876e0dfbaf11eaa6f5a01efb.tgz</li>
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>                        
            `;
        }
        if(this._regionid == "south_sudan") {
            return html`
            <nav-title .nav="${nav}"></nav-title>
            <ul>
                <li>An example of the PIHM Model for the Pongo basin in South Sudan can be browsed by using
                    <a href="https://files.mint.isi.edu/s/oLw76x6chUNXOc0/download">this Notebook</a>
                    (Wolfram Mathematica CDF player is needed to visualize and change the results of the notebook)
                </li>

                <li>
                    Alternatively, you may browse <a href="https://files.mint.isi.edu/s/tmn7sRjjPh7BZvK/download">this PDF</a>
                    for a non-interactive version of the example.
                </li>
            </ul>
            `;
        }
    }

    /*
    protected firstUpdated() {
        db.collectionGroup('pathways')
            .where('last_update.parameters.time', '>', 0)
            .get().then((snapshot) => {
                snapshot.docs.map((doc) => {
                    let pathway = doc.data() as Pathway;
                    Object.values(pathway.executable_ensemble_summary).map((summary: ExecutableEnsembleSummary) => {
                        if(summary.total_runs == summary.successful_runs && summary.total_runs > 400) {
                            console.log(pathway.id);
                        }
                    })
                })
            })
    }
    */

    stateChanged(state: RootState) {
        super.setRegionId(state);
    }
}

