fragment emulator_execution_info on execution {
    id
    start_time
    end_time
    status
    run_progress
    run_id
    execution_engine
    modelcatalog_configuration {
        id
    }
    parameter_bindings {
        modelcatalog_parameter {
            label
        }
        parameter_value
    }
    data_bindings {
        model_io {
            name
        }
        resource {
            id
            name
            url
        }
    }
    results {
        model_output {
            name
        }
        resource {
            id
            name
            url
        }
    }
}