query model_inputs_for_model($regionId: String!, $modelType: String!) {
  modelcatalog_parameter(distinct_on: label, where: {
    has_fixed_value: {
      _is_null:true
    }
    configuration_parameters: {
      configuration: {
        label: {_eq: $modelType},
        thread_models: {
          thread: {
            _or: [
              {region_id: {_eq: $regionId}},
              {region: {parent_region_id: {_eq: $regionId}}}
            ]
          }
        }
      }
    }
  }) {
    label
    has_data_type
  }
  model_inputs: model_io(distinct_on: name, where: {model_inputs: {model: {model_name: {_eq: $modelType}, thread_models: {thread: {_or: [{region_id: {_eq: $regionId}}, {region: {parent_region_id: {_eq: $regionId}}}]}}}}}) {
    name
    type
  }
  model_outputs: model_io(distinct_on: name, where: {model_outputs: {model: {model_name: {_eq: $modelType}, thread_models: {thread: {_or: [{region_id: {_eq: $regionId}}, {region: {parent_region_id: {_eq: $regionId}}}]}}}}}) {
    name
    type
  }
}
