query model_inputs_for_model_config($regionId: String!, $modelConfiguration: String!) {
  modelcatalog_parameter(distinct_on: label, where: {configuration_parameters: {configuration: {id: {_eq: $modelConfiguration}, thread_models: {thread: {_or: [{region_id: {_eq: $regionId}}, {region: {parent_region_id: {_eq: $regionId}}}]}}}}}) {
    label
    has_data_type
  }
  model_io(distinct_on: name, where: {model_inputs: {model: {model_configuration: {_eq: $modelConfiguration}, thread_models: {thread: {_or: [{region_id: {_eq: $regionId}}, {region: {parent_region_id: {_eq: $regionId}}}]}}}}}) {
    name
    type
  }
}
