query model_executions($modelTypes: [String!], $regionId: String!) {
  modelcatalog_configuration(where: {label: {_in: $modelTypes}}, order_by: {thread_models_aggregate: {count: desc}}) {
    id
    label
    description
    thread_models(order_by: {executions_aggregate: {count: desc}}, where: {thread: {task: {problem_statement: {region: {id: {_eq: $regionId}}}}}}) {
      thread {
        id
        name
        start_date
        end_date
        task {
          id
          name
          region {
            name
          }
          problem_statement {
            id
            name
            region {
              name
            }
          }
        }
      }
      modelcatalog_configuration {
        parameters {
          parameter {
            label
            has_fixed_value
          }
        }
        inputs {
          input {
            id
            label
          }
        }
      }
      data_bindings_aggregate {
        nodes {
          dataslice {
            resources(where:{selected:{_eq: true}}) {
              resource {
                name
                url
              }
            }
          }
          model_io {
            name
          }
        }
      }
      parameter_bindings_aggregate {
        nodes {
          model_parameter {
            name
          }
          parameter_value
        }
      }
      executions_aggregate(where: {execution: {status: {_eq: "SUCCESS"}}}) {
        aggregate {
          count
        }
      }
    }
  }
}
