query thread_executions($threadId: uuid!) {
  thread(where: {id: {_eq: $threadId}}) {
    id
    thread_models {
      modelcatalog_configuration {
        id
        label
        description
      }
      executions {
        execution {
          parameter_bindings {
            modelcatalog_parameter {
              label
            }
            parameter_value
          }
          data_bindings {
            model_io {
              name
            }
            resource {
              name
              url
            }
          }
          results {
            model_output {
              name
            }
            resource {
              name
              url
            }
          }
        }
      }
    }
  }
}
